In [3]:
pip install gdeltdoc

Requirement already satisfied: gdeltdoc in /Users/nsusser/opt/anaconda3/lib/python3.8/site-packages (1.5.0)
Requirement already satisfied: pandas>=1.1.4 in /Users/nsusser/opt/anaconda3/lib/python3.8/site-packages (from gdeltdoc) (2.0.3)
Requirement already satisfied: requests>=2.25.1 in /Users/nsusser/opt/anaconda3/lib/python3.8/site-packages (from gdeltdoc) (2.32.3)
Requirement already satisfied: tzdata>=2022.1 in /Users/nsusser/opt/anaconda3/lib/python3.8/site-packages (from pandas>=1.1.4->gdeltdoc) (2024.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/nsusser/opt/anaconda3/lib/python3.8/site-packages (from pandas>=1.1.4->gdeltdoc) (2.9.0.post0)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /Users/nsusser/opt/anaconda3/lib/python3.8/site-packages (from pandas>=1.1.4->gdeltdoc) (1.24.4)
Requirement already satisfied: pytz>=2020.1 in /Users/nsusser/opt/anaconda3/lib/python3.8/site-packages (from pandas>=1.1.4->gdeltdoc) (2024.2)
Requirement already satisfied: certifi>=2017.4.17 in /Users/nsusser/opt/anaconda3/lib/python3.8/site-packages (from requests>=2.25.1->gdeltdoc) (2020.6.20)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/nsusser/opt/anaconda3/lib/python3.8/site-packages (from requests>=2.25.1->gdeltdoc) (1.25.11)
Requirement already satisfied: idna<4,>=2.5 in /Users/nsusser/opt/anaconda3/lib/python3.8/site-packages (from requests>=2.25.1->gdeltdoc) (2.10)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/nsusser/opt/anaconda3/lib/python3.8/site-packages (from requests>=2.25.1->gdeltdoc) (3.4.0)
Requirement already satisfied: six>=1.5 in /Users/nsusser/opt/anaconda3/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas>=1.1.4->gdeltdoc) (1.15.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
from gdeltdoc import GdeltDoc, Filters

/Users/nsusser/opt/anaconda3/lib/python3.8/site-packages/pandas/core/computation/expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [5]:
f = Filters(
    keyword = 'Tesla',
    start_date = '2020-01-08',
    end_date = '2023-01-09'
)
gd = GdeltDoc()

In [6]:
articles = gd.article_search(f)
articles

,url,url_mobile,title,seendate,socialimage,domain,language,sourcecountry
0,https://udn.com/news/story/6811/6823928,https://udn.com/news/amp/story/6811/6823928,馬斯克接班人 ？ 中籍朱曉彤傳獲任特斯拉全球CEO | 全球財經 | 全球,20221208T091500Z,https://uc.udn.com.tw/photo/wj/realtime/2022/1...,udn.com,Chinese,Taiwan
1,https://finance.sina.com.cn/tech/it/2022-12-08...,,特斯拉中国负责人朱晓彤升任特斯拉CEO ？ 外媒 ： 马斯克钦点他来得州工厂抓产能,20221208T081500Z,https://n.sinaimg.cn/finance/transform/667/w40...,finance.sina.com.cn,Chinese,China
2,http://global.eastmoney.com/a/2022120925841854...,,传闻中的马斯克接班人 _ 东方财富网,20221209T153000Z,,global.eastmoney.com,Chinese,China
3,https://cleantechnica.com/2022/10/13/tesla-cre...,https://cleantechnica.com/2022/10/13/tesla-cre...,Tesla Creates Energy Use Breakdown For Drivers...,20221013T171500Z,https://cleantechnica.com/files/2022/10/Tesla-...,cleantechnica.com,English,United States
4,https://www.163.com/dy/article/HJGQLLOH0511B8L...,,特斯拉占 8 月美国电动汽车销量的 2 / 3 ， Model Y / 3 霸榜,20221012T144500Z,,163.com,Chinese,China
...,...,...,...,...,...,...,...,...
245,https://www.chinapress.com.my/20230108/%E4%B8%...,https://www.chinapress.com.my/20230108/%e4%b8%...,中国特斯拉降价 引发部分近期购车者抗议 | 中國報 China Press,20230108T110000Z,https://www.chinapress.com.my/wp-content/uploa...,chinapress.com.my,Chinese,Malaysia
246,https://www.163.com/tech/article/HQKIVS6M00097...,,特斯拉最大散户投资者成马斯克头号反对者 ： 我投资了30多亿美元,20230109T011500Z,,163.com,Chinese,China
247,https://technews.tw/2023/01/09/tesla-short-sel...,,特斯拉空軍 2022 年暴賺 ， 股價沒起色遭加碼放空,20230109T094500Z,https://img.technews.tw/wp-content/uploads/202...,technews.tw,Chinese,Taiwan
248,https://news.cnyes.com/news/id/5030479,https://amp-news.cnyes.com/news/id/5030479,Bernstein分析師 ： 特斯拉有需求問題 利潤恐受壓 | Anue鉅亨,20221208T031500Z,https://cimg.cnyes.cool/prod/news/5030479/l/f8...,news.cnyes.com,Chinese,China
249,https://www.focus.de/panorama/welt/in-duerrste...,https://amp.focus.de/panorama/welt/in-duerrste...,Tesla will selbstständig Wasser für Brandenbur...,20221207T080000Z,https://p6.focus.de/img/kultur/vermischtes/id_...,focus.de,German,Germany

In [7]:
timeline = gd.timeline_search('timelinevol', f)
timeline

                      datetime  Volume Intensity
0    2020-01-08 00:00:00+00:00            0.3274
1    2020-01-09 00:00:00+00:00            0.3265
2    2020-01-10 00:00:00+00:00            0.2454
3    2020-01-11 00:00:00+00:00            0.1813
4    2020-01-12 00:00:00+00:00            0.1895
...                        ...               ...
1092 2023-01-05 00:00:00+00:00            0.5036
1093 2023-01-06 00:00:00+00:00            0.5902
1094 2023-01-07 00:00:00+00:00            0.4116
1095 2023-01-08 00:00:00+00:00            0.3704
1096 2023-01-09 00:00:00+00:00            0.4074

[1097 rows x 2 columns]

In [8]:
timeline_lang = gd.timeline_search('timelinelang', f)
timeline_lang

,datetime,Albanian Volume Intensity,Lithuanian Volume Intensity,Malayalam Volume Intensity,Swedish Volume Intensity,Hungarian Volume Intensity,Dutch Volume Intensity,Persian Volume Intensity,Ukrainian Volume Intensity,Telugu Volume Intensity,...,Bengali Volume Intensity,Polish Volume Intensity,Danish Volume Intensity,Azerbaijani Volume Intensity,Norwegian Volume Intensity,Korean Volume Intensity,Italian Volume Intensity,Indonesian Volume Intensity,Chinese Volume Intensity,English Volume Intensity
0,2020-01-08 00:00:00+00:00,0.0,0.0000,0.0,0.5995,0.0000,0.1445,0.0000,0.0000,0.0,...,0.0000,0.2107,0.0,0.0,0.0893,0.3096,0.0056,0.0,1.9010,0.2078
1,2020-01-09 00:00:00+00:00,0.0,0.0000,0.0,0.7784,0.0000,0.0000,0.0000,0.0000,0.0,...,0.0000,0.3052,0.0,0.0,0.1832,0.1779,0.0000,0.0,1.4595,0.2800
2,2020-01-10 00:00:00+00:00,0.0,0.0000,0.0,0.1450,0.0000,0.3019,0.0000,0.0000,0.0,...,0.0000,0.1354,0.0,0.0,0.1826,0.0694,0.0000,0.0,1.2676,0.2077
3,2020-01-11 00:00:00+00:00,0.0,0.0000,0.0,0.0000,0.0000,0.0000,0.6410,0.0000,0.0,...,0.0000,0.0692,0.0,0.0,0.1531,0.0774,0.0000,0.0,0.6001,0.2160
4,2020-01-12 00:00:00+00:00,0.0,0.0000,0.0,0.0296,0.0000,0.0000,0.3559,0.0000,0.0,...,0.0625,0.1993,0.0,0.0,0.0000,0.1515,0.0000,0.0,1.1918,0.1332
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1092,2023-01-05 00:00:00+00:00,0.0,0.0000,0.0,0.4505,0.0000,0.0760,0.5236,0.0000,0.0,...,0.1639,0.2456,0.0,0.0,0.0000,1.4058,0.0000,0.0,1.3987,0.6478
1093,2023-01-06 00:00:00+00:00,0.0,0.0779,0.0,0.3530,0.0000,0.0387,0.4545,0.0288,0.0,...,0.0000,0.3808,0.0,0.0,0.0000,1.5274,0.0000,0.0,1.8328,0.6917
1094,2023-01-07 00:00:00+00:00,0.0,0.3690,0.0,1.4760,0.1631,0.0460,0.0000,0.0000,0.0,...,0.0856,0.2671,0.0,0.0,0.0000,1.6077,0.0000,0.0,1.6497,0.4668
1095,2023-01-08 00:00:00+00:00,0.0,0.0000,0.0,0.1792,0.0000,0.0000,0.0000,0.0000,0.0,...,0.0000,0.2562,0.0,0.0,0.0000,1.3973,0.0000,0.0,1.0693,0.5402
1096,2023-01-09 00:00:00+00:00,0.0,0.0000,0.0,0.3924,0.0000,0.0742,0.0000,0.0000,0.0,...,0.0736,0.2923,0.0,0.0,0.0000,1.4575,0.0000,0.0,1.5866,0.5126

In [9]:
timeline_tone = gd.timeline_search('timelinetone', f)
timeline_tone

                      datetime  Average Tone
0    2020-01-08 00:00:00+00:00        0.7657
1    2020-01-09 00:00:00+00:00        0.3329
2    2020-01-10 00:00:00+00:00        0.5371
3    2020-01-11 00:00:00+00:00        0.4848
4    2020-01-12 00:00:00+00:00        0.5093
...                        ...           ...
1092 2023-01-05 00:00:00+00:00       -1.3056
1093 2023-01-06 00:00:00+00:00       -0.4258
1094 2023-01-07 00:00:00+00:00       -0.5393
1095 2023-01-08 00:00:00+00:00       -1.6367
1096 2023-01-09 00:00:00+00:00       -0.5392

[1097 rows x 2 columns]

In [10]:
t = Filters(
    keyword = 'tech',
    start_date = '2022-01-01',
    end_date = '2023-01-01'
)
articles = gd.article_search(f)
articles

,url,url_mobile,title,seendate,socialimage,domain,language,sourcecountry
0,https://udn.com/news/story/6811/6823928,https://udn.com/news/amp/story/6811/6823928,馬斯克接班人 ？ 中籍朱曉彤傳獲任特斯拉全球CEO | 全球財經 | 全球,20221208T091500Z,https://uc.udn.com.tw/photo/wj/realtime/2022/1...,udn.com,Chinese,Taiwan
1,https://finance.sina.com.cn/tech/it/2022-12-08...,,特斯拉中国负责人朱晓彤升任特斯拉CEO ？ 外媒 ： 马斯克钦点他来得州工厂抓产能,20221208T081500Z,https://n.sinaimg.cn/finance/transform/667/w40...,finance.sina.com.cn,Chinese,China
2,http://global.eastmoney.com/a/2022120925841854...,,传闻中的马斯克接班人 _ 东方财富网,20221209T153000Z,,global.eastmoney.com,Chinese,China
3,https://cleantechnica.com/2022/10/13/tesla-cre...,https://cleantechnica.com/2022/10/13/tesla-cre...,Tesla Creates Energy Use Breakdown For Drivers...,20221013T171500Z,https://cleantechnica.com/files/2022/10/Tesla-...,cleantechnica.com,English,United States
4,https://www.163.com/dy/article/HJGQLLOH0511B8L...,,特斯拉占 8 月美国电动汽车销量的 2 / 3 ， Model Y / 3 霸榜,20221012T144500Z,,163.com,Chinese,China
...,...,...,...,...,...,...,...,...
245,https://www.chinapress.com.my/20230108/%E4%B8%...,https://www.chinapress.com.my/20230108/%e4%b8%...,中国特斯拉降价 引发部分近期购车者抗议 | 中國報 China Press,20230108T110000Z,https://www.chinapress.com.my/wp-content/uploa...,chinapress.com.my,Chinese,Malaysia
246,https://www.163.com/tech/article/HQKIVS6M00097...,,特斯拉最大散户投资者成马斯克头号反对者 ： 我投资了30多亿美元,20230109T011500Z,,163.com,Chinese,China
247,https://technews.tw/2023/01/09/tesla-short-sel...,,特斯拉空軍 2022 年暴賺 ， 股價沒起色遭加碼放空,20230109T094500Z,https://img.technews.tw/wp-content/uploads/202...,technews.tw,Chinese,Taiwan
248,https://news.cnyes.com/news/id/5030479,https://amp-news.cnyes.com/news/id/5030479,Bernstein分析師 ： 特斯拉有需求問題 利潤恐受壓 | Anue鉅亨,20221208T031500Z,https://cimg.cnyes.cool/prod/news/5030479/l/f8...,news.cnyes.com,Chinese,China
249,https://www.focus.de/panorama/welt/in-duerrste...,https://amp.focus.de/panorama/welt/in-duerrste...,Tesla will selbstständig Wasser für Brandenbur...,20221207T080000Z,https://p6.focus.de/img/kultur/vermischtes/id_...,focus.de,German,Germany

In [11]:
Yes, I understand the possible function calls to the GDELT dataset API using the `gdeltdoc` library. Here are the main functions you can use:

1. **Article Search**: This function searches for news articles based on the specified filters.
    ```python
    articles = gd.article_search(f)
    ```

2. **Timeline Search**: This function searches for timelines based on the specified filters and timeline type.
    ```python
    timeline = gd.timeline_search('timelinevol', f)  # Volume timeline
    timeline_lang = gd.timeline_search('timelinelang', f)  # Language timeline
    timeline_tone = gd.timeline_search('timelinetone', f)  # Tone timeline
    ```

3. **Event Search**: This function searches for events based on the specified filters.
    ```python
    events = gd.event_search(f)
    ```

4. **Mention Search**: This function searches for mentions based on the specified filters.
    ```python
    mentions = gd.mention_search(f)
    ```

5. **Export Search**: This function exports search results based on the specified filters.
    ```python
    export = gd.export_search(f)
    ```

These functions allow you to interact with the GDELT dataset and retrieve various types of data based on your filters.

SyntaxError: invalid syntax (709081903.py, line 1)

In [12]:
f = Filters(
    keyword = 'Tesla',
    start_date = '2020-01-01',
    end_date = '2023-01-01',
)
articles = gd.article_search(f)
articles

,url,url_mobile,title,seendate,socialimage,domain,language,sourcecountry
0,https://bbs.wenxuecity.com/bbs/financenews/206...,,财经新闻 ： 暴跌16 ％， 特斯拉的 噩梦一周 - 由华尔街见闻发表,20221009T030000Z,,bbs.wenxuecity.com,Chinese,China
1,https://udn.com/news/story/6811/6823928,https://udn.com/news/amp/story/6811/6823928,馬斯克接班人 ？ 中籍朱曉彤傳獲任特斯拉全球CEO | 全球財經 | 全球,20221208T091500Z,https://uc.udn.com.tw/photo/wj/realtime/2022/1...,udn.com,Chinese,Taiwan
2,https://finance.sina.com.cn/tech/it/2022-12-08...,,特斯拉中国负责人朱晓彤升任特斯拉CEO ？ 外媒 ： 马斯克钦点他来得州工厂抓产能,20221208T081500Z,https://n.sinaimg.cn/finance/transform/667/w40...,finance.sina.com.cn,Chinese,China
3,https://k.sina.com.cn/article_6501717613_18388...,,买特斯拉先等等 ， 送7000元保费或许只是刚开始 ， 降价4万有望成真,20221009T060000Z,http://n.sinaimg.cn/sinakd20109/630/w915h515/2...,k.sina.com.cn,Chinese,China
4,https://www.163.com/dy/article/HJ8MLVLQ051100B...,,卖爆了 ！ 特斯拉中国9月交付超8 . 3万辆 ： 再创月度交付新记录,20221009T121500Z,,163.com,Chinese,China
...,...,...,...,...,...,...,...,...
245,https://www.news1.kr/articles/?4874216,https://www.news1.kr/amp/articles/?4874216,"테슬라 7 . 82 %- 니콜라 3 . 48 %, 美전기차 일제↑ ( 종합 )",20221123T234500Z,https://image.news1.kr/system/photos/2022/11/2...,news1.kr,Korean,South Korea
246,http://hy.stock.cnfol.com/nonglinmuyu/20221209...,,WeLab Bank汇立银行与特斯拉确立战略合作 ： 整合生态圈 ， 共创全新用户体验 _ ...,20221209T110000Z,,hy.stock.cnfol.com,Chinese,China
247,https://www.stern.de/wirtschaft/elon-musk--med...,https://www.stern.de/amp/wirtschaft/elon-musk-...,Elon Musk : Medienbericht über Rückzug bei Tes...,20221208T164500Z,https://image.stern.de/32989956/t/ts/v3/w1440/...,stern.de,German,Germany
248,https://www.163.com/tech/article/HNT20MKD00097...,,外媒 ： 工资低福利差 ， 特斯拉柏林工厂招人困难,20221206T011500Z,,163.com,Chinese,China
249,https://www.chinatimes.com/realtimenews/202211...,https://www.chinatimes.com/amp/realtimenews/20...,《 國際產業 》 花旗調升評級 、 目標價 特斯拉股價飆漲近8 % - 財經,20221124T091500Z,,chinatimes.com,Chinese,Taiwan

In [22]:
import pandas as pd
# Create an empty DataFrame to store all news data
all_news_data = pd.DataFrame()

# Loop through each ticker symbol in the constituents DataFrame
for ticker in constituents['Symbol']:
    # Set the filter for the current ticker
    f = Filters(
        keyword=ticker,
        start_date='2016-01-01',
        end_date='2023-01-01'
    )
    
    # Search for articles related to the current ticker
    articles = gd.article_search(f)
    
    # Add a column for the ticker symbol
    articles['Ticker'] = ticker
    
    # Append the articles to the all_news_data DataFrame
    all_news_data = pd.concat([all_news_data, articles], ignore_index=True)

# Display the combined news data
all_news_data

ValueError: The query was not valid. The API error message was: Invalid query start date.

In [19]:
import pandas as pd
constituents = pd.read_csv('constituents.csv')
# Create an empty DataFrame to store all news data
all_news_data = pd.DataFrame()

# Loop through each ticker symbol in the constituents DataFrame
for ticker in constituents['Symbol']:
    # Set the filter for the current ticker
    f = Filters(
        keyword=ticker,
        start_date='2016-01-01',
        end_date='2023-01-01'
    )
    
    # Search for articles related to the current ticker
    articles = gd.article_search(f)
    
    # Add a column for the ticker symbol
    articles['Ticker'] = ticker
    
    # Append the articles to the all_news_data DataFrame
    all_news_data = pd.concat([all_news_data, articles], ignore_index=True)

# Display the combined news data
all_news_data

ValueError: The query was not valid. The API error message was: Invalid query start date.